[[pages]]
path = "pages/dashboard.py"
name = "Ğ“Ğ¾Ğ»Ğ¾Ğ²Ğ½Ğ°"
icon = "ğŸ“„"

[[pages]]
path = "pages/data.py"
name = "Ğ”Ğ°Ñ‚Ğ°ÑĞµÑ‚Ğ¸"
icon = "ğŸ“Š"

[[pages]]
path = "pages/exp_page.py"
name = "Ğ•ĞºÑĞ¿ĞµÑ€Ğ¸Ğ¼ĞµĞ½Ñ‚"
icon = "ğŸ”¬"

[[pages]]
path = "pages/exp_comparing.py"
name = "ĞŸĞ¾Ñ€Ñ–Ğ²Ğ½ÑĞ½Ğ½Ñ"
icon = "âš–ï¸"

[[pages]]
path = "pages/docs.py"
name = "Ğ”Ğ¾ĞºÑƒĞ¼ĞµĞ½Ñ‚Ğ°Ñ†Ñ–Ñ"
icon = "ğŸ—‚ï¸"

[[pages]]
path = "pages/settings.py"
name = "ĞĞ°Ğ»Ğ°ÑˆÑ‚ÑƒĞ²Ğ°Ğ½Ğ½Ñ"
icon = "âš™ï¸"

